packages:
  - "integration-tests/**"
  - "packages/**"
  - "!**/dist/**"
  - "!**/temp/**"
  - "!**/test-data/**"
  - "!**/__snapshots/**"

catalog:
  "@babel/generator": ^7.29.1
  "@babel/template": ^7.28.6
  "@babel/types": ^7.29.0
  "@pnpm/lockfile.fs": ^1001.1.29
  "@pnpm/lockfile.utils": ^1004.0.1
  "@pnpm/lockfile.walker": ^1001.0.24
  "@pnpm/types": ^1001.3.0
  "@pnpm/logger": ^1001.0.1
  "@rollup/plugin-node-resolve": ^16.0.3
  "@rollup/pluginutils": ^5.3.0
  chalk: ^5.6.2
  commander: ^14.0.3
  debug: ^4.4.3
  esbuild: ^0.27.3
  find-git-root: ^1.1.0
  find-workspaces: ^0.3.1
  fs-extra: ^11.3.3
  import-meta-resolve: ^4.2.0
  js-yaml: ^4.1.1
  oxc-resolver: ^11.17.1
  postcss-import: ^16.1.1
  postcss: ^8.5.6
  prettier: ^3.8.1
  rollup-plugin-esbuild: ^6.2.1
  rollup: ^4.57.1
  sass: ^1.97.3
  semver: ^7.7.4
  tinyglobby: ^0.2.15
  typescript: ^5.9.3
  vitefu: ^1.1.1
  zod-validation-error: ^5.0.0
  zod: ^4.3.6
  zx: ^8.8.5

  # Dev tooling
  "@changesets/cli": ^2.29.8
  "@types/babel__generator": ^7.27.0
  "@types/babel__template": ^7.4.4
  "@types/debug": ^4.1.12
  "@types/fs-extra": ^11.0.4
  "@types/js-yaml": ^4.0.9
  "@types/node": ^20.19.33
  "@types/postcss-import": ^14.0.3
  "@types/react": ^19.2.14
  "@types/semver": ^7.7.1
  "@typescript-eslint/parser": ^8.55.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-headers: ^1.3.4
  eslint-plugin-import: ^2.32.0
  eslint-plugin-unused-imports: ^4.4.1
  eslint: ^9.39.2
  "@eslint/js": ^9.39.2
  "typescript-eslint": ^8.55.0
  husky: ^9.1.7
  lint-staged: ^16.2.7
  rimraf: ^6.1.2
  vite: ^7.3.1
  vitest: ^4.0.18

catalogs:
  # Used in integration tests, no need to keep these up to date
  tests:
    "@chakra-ui/icons": 2.1.1
    "@open-pioneer/chakra-integration": 1.1.3
    "@open-pioneer/core": 1.2.3
    "@open-pioneer/http": 2.1.8
    "@open-pioneer/map": 0.5.1
    "@open-pioneer/runtime": ">= 2.2.0"
    "@open-pioneer/react-utils": 0.2.3
    "@open-pioneer/test-utils": ^1.1.3
    "@types/proj4": 2.5.5
    "@types/jsdom": ^21.1.7
    "@types/react-dom": 18.3.0
    "@types/uuid": ^10.0.0
    classnames: ^2.5.1
    chakra-react-select: 4.9.1
    ol: 9.2.4
    proj4: 2.11.0
    react-dom: 18.3.1
    react-select: 5.8.0
    react-use: 17.5.1
    react: 18.3.1
    uuid: 10.0.0

# Install older versions by default
resolutionMode: "lowest-direct"

# Configure a release cooldown
minimumReleaseAge: 4320 # 3 days in minutes
minimumReleaseAgeExclude:
  - "@open-pioneer/*"
  - "@conterra/*"
  - "@isaacs/brace-expansion@5.0.1" # see overrides

overrides:
  # https://github.com/advisories/GHSA-7h2j-956f-4vf2
  "@isaacs/brace-expansion@<=5.0.0": "^5.0.1"

  # Version doesn't really matter, this is used as a dep in integration tests
  "@open-pioneer/runtime": ">= 2.2.0"

auditConfig:
  ignoreCves:
    # This affects ajv, which is a transitive dependency of eslint.
    # Eslint depends on ajv@v6, and an update to v8 might not be trivial.
    # Only dev dependencies are (potentially) affected.
    # https://github.com/advisories/GHSA-2g4f-4pwh-qvx6
    - CVE-2025-69873

allowUnusedPatches: true
ignorePatchFailures: false
patchedDependencies: {}

peerDependencyRules:
  allowedVersions:
    # Versions don't really matter, these are used as deps in integration tests
    "@open-pioneer/chakra-integration>framer-motion": ">=4.0.0"
    "@open-pioneer/base-theme": "*"
    "@open-pioneer/chakra-integration@^2.2.0": "*"
    "@open-pioneer/runtime-react-support@^1.0.2": "*"
    "@open-pioneer/core": "*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild

ignoredBuiltDependencies:
  # Seems to work fine without building
  - unrs-resolver

# Workaround for current problems regarding our vite plugin + vite's optimizeDeps feature
shamefullyHoist: true

linkWorkspacePackages: false
strictPeerDependencies: true
