packages:
    - "." # workaround for https://github.com/changesets/changesets/issues/1133 (packages don't find build-tools repo root)
    - "integration-tests/**"
    - "packages/**"
    - "!**/dist/**"
    - "!**/temp/**"
    - "!**/test-data/**"
    - "!**/__snapshots/**"
