#!/usr/bin/env sh
if [ "$NO_VERIFY" ]; then
    echo 'pre-commit hook skipped' 1>&2
    exit 0
fi

. "$(dirname -- "$0")/_/husky.sh"

echo '--- run linting --- '
pnpm run lint

echo '--- run prettier ---'
pnpm run prettier-check

echo '--- run typescript check ---'
pnpm run check-types

echo '--- run tests ---'
pnpm run clean
pnpm run build
pnpm run test run

