name: Audit dependencies (daily)

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  audit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
          
      - name: Audit dependencies
        run: pnpm audit
