name: Run tests
on:
  - workflow_dispatch
  - workflow_call
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Runs checks
        run: |
          pnpm run ci:test

  call_version:
    if: github.ref == 'refs/heads/main'
    name: "Publish or create version PR"
    uses: "./.github/workflows/version.yml"
    needs: test
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
