name: Open Pioneer Actions
on: 
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm i
      
      - name: Check lint
        run: pnpm lint

      - name: Build app
        run: pnpm build

      - name: Run tests
        run: pnpm vitest run
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          repository-name: open-pioneer/demo
          token: ${{ secrets.DEPLOY_TOKEN }}
          folder: dist

      - run: echo "This job's status is ${{ job.status }}."
