name: Build and deploy
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code style
        run: |
          pnpm run lint;
          pnpm run check-types;

      - name: Run tests
        run: pnpm run test

      - name: Build
        run: |
          pnpm run clean;
          pnpm run build;
