name: Run tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: "Test and Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install
        uses: open-pioneer/trails-repo-automation/.github/actions/install@799b38eabbb77b18ff1d9177630fd7920e86433d # main

      - name: Run checks
        run: |
          pnpm run ci:test

  call_version:
    if: github.ref == 'refs/heads/main'
    name: "Publish or create version PR"
    uses: "./.github/workflows/version.yml"
    needs: test
    permissions:
      contents: write
      pull-requests: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
