name: Run tests
on:
  - workflow_dispatch
  - workflow_call
  - push
  - pull_request

jobs:
  test:
    # Don't run for pull requests from this repository to avoid duplicate builds (push also triggers build).
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: "Test and Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install
        uses: open-pioneer/trails-repo-automation/.github/actions/install@main

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run checks
        run: |
          pnpm run ci:test

  call_version:
    if: github.ref == 'refs/heads/main'
    name: "Publish or create version PR"
    uses: "./.github/workflows/version.yml"
    needs: test
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
